### ISSUE TITLE
Defunctorization

### ISSUE THREAD

**Issue by DemiMarie** [ocaml-flambda/flambda-backend#963]
In cases not involving recursive or first-class modules, my understanding is that it is possible to perform defunctorization to eliminate all functor overhead.

**Comment by lthls** [comment]
Could you explain what you think is currently missing ? As far as I can tell if you annotate all your functors with `[@@inline always]` that should give you the result you're describing.

**Comment by DemiMarie** [comment]
> Could you explain what you think is currently missing ? As far as I can tell if you annotate all your functors with `[@@inline always]` that should give you the result you're describing.

Should this be done with most stdlib functors?  Coq has had to use `Obj.magic` to work around this.

**Comment by lthls** [comment]
> Should this be done with most stdlib functors?

No, because it is not always the best solution. If you need to defunctorise the functors from the Stdlib, either mark all their uses with `[@inlined]` or re-export them (e.g. `module SetMake (X : Set.OrderedType) = (Set.Make[@inlined])(X) [@@inline]`). But in many cases it's just better to let the compiler choose whether to inline or not. Typically, if compilation time or binary size are important then systematic inlining is not a good idea.

> Coq has had to use `Obj.magic` to work around this.

I have no idea what this has to do with the current topic. Could you point to some discussion or piece of code ?

**Comment by DemiMarie** [comment]
> > Should this be done with most stdlib functors?
> 
> No, because it is not always the best solution. If you need to defunctorise the functors from the Stdlib, either mark all their uses with `[@inlined]` or re-export them (e.g. `module SetMake (X : Set.OrderedType) = (Set.Make[@inlined])(X) [@@inline]`). But in many cases it's just better to let the compiler choose whether to inline or not. Typically, if compilation time or binary size are important then systematic inlining is not a good idea.

For some context: I have often wished OCaml had something like [MLton](/mlton/mlton).

> > Coq has had to use `Obj.magic` to work around this.
> 
> I have no idea what this has to do with the current topic. Could you point to some discussion or piece of code ?

https://github.com/coq/coq/issues/7839#issue-332981823

**Comment by lthls** [comment]
I still don't understand the issue with Coq, but overall it looks like there isn't anything we need to fix or implement.
Unless you can provide a specific example of code that is not compiled the way you'd like it to, I'm going to close this issue.
